# @package _global_

# specify here default training configuration
defaults:
  - _self_
  - trainer: default
  - optimizer: adam
  - scheduler: step
  - logger: mlflow
  - model: mlp

# global configurations
experiment_name: Default
gpus: -1
lr: 1e-6
epochs: 50
batch_size: 512
feature_length: 64
train_test_rate: 0.8

is_bond_prior: true
is_angle_prior: true
is_dihedral_prior: true

scale: 1e5

# path to original working directory (that `run.py` was executed from in command line)
# hydra hijacks working directory by changing it to the current log directory,
# so it's useful to have path to original work dir as a special variable
# read more here: https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
work_dir: ${hydra:runtime.cwd}

# dataset path
coordinates: /home/bokutotu/HDD/Lab/python_preprocess/removed_c_trj.npy
forces: /home/bokutotu/HDD/Lab/python_preprocess/removed_f_trj.npy

hydra:
    # output paths for hydra logs
    run:
        dir: /tmp/logs/runs/${now:%Y-%m-%d}/${now:%H:%M:%S}/${hydra.job.override_dirname}
    sweep:
        dir: logs/multiruns/${now:%Y-%m-%d}/${now:%H:%M:%S}/
        subdir: ${hydra.job.override_dirname}

    job:
      # you can set here environment variables that are universal for all users
      # for system specific variables (like data paths) it's better to use .env file!
      # env_set:
      config:
        # configuration for the ${hydra.job.override_dirname} runtime variable
        override_dirname:
          kv_sep: '='
          item_sep: '/'
